spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ithubevents?serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
  main:
    allow-bean-definition-overriding: true

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/ithubevents?serverTimezone=UTC
    skip-default-callbacks: true
